name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build Node.js"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: "Execute build"
        run: |
          npm ci
          npm run build

      # temporarily disabled, as `z-schema` as a `@veramo/core@5.5.3` is not transformed to ESM from CommonJS properly
      # otherwise, tests pass by removing z-schema object validator as a workaround
      # - name: "Execute tests"
      #   run: npm test
